
#define XBOX_ANALOG_LEFT_JOY_X 0
#define XBOX_ANALOG_LEFT_JOY_Y 1
#define XBOX_ANALOG_LEFT_TRIGGER 2

#define XBOX_ANALOG_RIGHT_JOY_X 3
#define XBOX_ANALOG_RIGHT_JOY_Y 4
#define XBOX_ANALOG_RIGHT_TRIGGER 5

#define XBOX_ANALOG_DPAD_X 6
#define XBOX_ANALOG_DPAD_Y 7

#define XBOX_DIGITAL_BUTTON_A 0
#define XBOX_DIGITAL_BUTTON_B 1
#define XBOX_DIGITAL_BUTTON_X 2
#define XBOX_DIGITAL_BUTTON_Y 3
#define XBOX_DIGITAL_BUTTON_RIGHT_BUMPER 5
#define XBOX_DIGITAL_BUTTON_LEFT_BUMPER 4
#define XBOX_DIGITAL_BUTTON_BACK 6
#define XBOX_DIGITAL_BUTTON_START 7
#define XBOX_DIGITAL_BUTTON_XBOX 8
#define XBOX_DIGITAL_BUTTON_LEFT_JOY 9
#define XBOX_DIGITAL_BUTTON_RIGHT_JOY 10
#define XBOX_DIGITAL_BUTTON_DPAD_LEFT 11
#define XBOX_DIGITAL_BUTTON_DPAD_RIGHT 12
#define XBOX_DIGITAL_BUTTON_DPAD_UP 13
#define XBOX_DIGITAL_BUTTON_DPAD_DOWN 14
