#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd ${SCRIPT_DIR}/../../../..

pwd
#ros_cross_compile /home/caseyg/ros_dev --arch armhf --os ubuntu --rosdistro foxy  --skip-rosdep-keys "robot_msgs robot_shared" --custom-setup-script /home/caseyg/ros_dev/src/ros2robot/scripts/dockerscripts/custom_setup.sh
ros_cross_compile ./ --arch armhf --os ubuntu --rosdistro dashing --skip-rosdep-keys "robot_msgs robot_shared" --custom-setup-script /home/caseyg/ros_dev/src/ros2robot/scripts/dockerscripts/custom_setup.sh
