#!/bin/bash


SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd ${SCRIPT_DIR}/../../../..


DOMAIN_ID=$1

if [ -z "$DOMAIN_ID" ] ; then
  DOMAIN_ID=2
  echo "using default DOMAIN_ID $DOMAIN_ID"
else
  echo "using Domain id $DOMAIN_ID"
 
fi

export ROS_DOMAIN_ID=$DOMAIN_ID
source /opt/ros/foxy/setup.bash 
ros2 run joy joy_node &
source install/setup.bash 
ros2 run lalosoft_robot_control_host control_host &
echo "done"