#!/bin/bash


host=$1

if [ -z "$host" ] ; then
  echo "using default host"
  host=cotsbotrott.local
else
  echo "using alternate host $1"
  host=$1
fi
gst-launch-1.0 -q -v playbin uri=rtsp://$host:8554/test uridecodebin0::source::latency=0

